/**
 * Slack Activities
 *
 * These activities send formatted messages to Slack channels.
 */

import { WebClient } from '@slack/web-api';
import dotenv from 'dotenv';
import logger from '../config/logger';
import { PRSummarySlackMessage, SlackBlock } from '../types';

dotenv.config();

// Initialize Slack client
function getSlackClient(): WebClient {
  const token = process.env.SLACK_BOT_TOKEN;

  if (!token) {
    throw new Error('SLACK_BOT_TOKEN environment variable is required');
  }

  return new WebClient(token);
}

/**
 * Activity: Send PR summary to Slack
 */
export async function sendPRSummaryToSlack(
  message: PRSummarySlackMessage,
  channel: string
): Promise<string> {
  const slack = getSlackClient();

  logger.info('Sending PR summary to Slack', {
    channel,
    prNumber: message.prNumber,
    repository: message.repository,
  });

  try {
    // Build rich Slack message blocks
    const blocks: SlackBlock[] = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `🔔 New PR: ${message.prTitle}`,
          emoji: true,
        },
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Repository:*\n${message.repository}`,
          },
          {
            type: 'mrkdwn',
            text: `*Author:*\n${message.author}`,
          },
          {
            type: 'mrkdwn',
            text: `*PR Number:*\n#${message.prNumber}`,
          },
          {
            type: 'mrkdwn',
            text: `*Commits:*\n${message.commitCount}`,
          },
          {
            type: 'mrkdwn',
            text: `*Base Branch:*\n\`${message.baseBranch}\``,
          },
          {
            type: 'mrkdwn',
            text: `*Head Branch:*\n\`${message.headBranch}\``,
          },
        ],
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*📝 Summary:*\n${message.summary}`,
        },
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `<${message.prUrl}|View Pull Request on GitHub →>`,
        },
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: '🤖 Generated by Temporal Vibe Automator',
          },
        ],
      },
    ];

    // Send message to Slack
    const result = await slack.chat.postMessage({
      channel,
      blocks,
      text: `New PR #${message.prNumber}: ${message.prTitle}`, // Fallback text
    });

    if (!result.ok) {
      throw new Error(`Slack API error: ${result.error}`);
    }

    const messageTs = result.ts || '';

    logger.info('Successfully sent PR summary to Slack', {
      channel,
      prNumber: message.prNumber,
      messageTs,
    });

    return messageTs;
  } catch (error) {
    logger.error('Failed to send PR summary to Slack', {
      channel,
      prNumber: message.prNumber,
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}

/**
 * Activity: Send a simple text message to Slack
 */
export async function sendSlackMessage(
  channel: string,
  text: string
): Promise<string> {
  const slack = getSlackClient();

  logger.info('Sending message to Slack', { channel });

  try {
    const result = await slack.chat.postMessage({
      channel,
      text,
    });

    if (!result.ok) {
      throw new Error(`Slack API error: ${result.error}`);
    }

    const messageTs = result.ts || '';

    logger.info('Successfully sent message to Slack', { channel, messageTs });

    return messageTs;
  } catch (error) {
    logger.error('Failed to send message to Slack', {
      channel,
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}
